In [2]:
import numpy as np
m = np.array([[1, 2],[2, 3]])
w, v = np.linalg.eig(m)
print("Printing the Eigen values of the given square array:\n",w)
print("Printing Right eigenvectors of the given square array:\n",v)

Printing the Eigen values of the given square array:
 [-0.23606798  4.23606798]
Printing Right eigenvectors of the given square array:
 [[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]


In [3]:
m = np.array([[1, 2, 3],
			[2, 3, 4],
			[4, 5, 6]])

w, v = np.linalg.eig(m)
print("Printing the Eigen values of the given square array:\n",w)
print("Printing Right eigenvectors of the given square array:\n",v)

Printing the Eigen values of the given square array:
 [ 1.08309519e+01 -8.30951895e-01  1.01486082e-16]
Printing Right eigenvectors of the given square array:
 [[ 0.34416959  0.72770285  0.40824829]
 [ 0.49532111  0.27580256 -0.81649658]
 [ 0.79762415 -0.62799801  0.40824829]]


In [4]:
import tensorflow as tf

In [6]:
e_matrix_A = tf.random.uniform([2, 2], minval=3, maxval=10, dtype=tf.float32, name="matrixA")
print("Matrix A: \n{}\n\n".format(e_matrix_A))
eigen_values_A, eigen_vectors_A = tf.linalg.eigh(e_matrix_A)
print("Eigen Vectors: \n{} \n\nEigen Values: \n{}\n".format(eigen_vectors_A, eigen_values_A))

Matrix A: 
[[7.8791924 3.7057962]
 [8.191602  4.6210017]]


Eigen Vectors: 
[[-0.63440764  0.7729987 ]
 [ 0.7729987   0.63440764]] 

Eigen Values: 
[-2.101926 14.60212 ]



In [7]:
eigen_values_A, eigen_vectors_A = tf.linalg.eigh(e_matrix_A)
print("Eigen Vectors: \n{} \n\nEigen Values: \n{}\n".format(eigen_vectors_A, eigen_values_A))
eigen_values_A, eigen_vectors_A = tf.linalg.eigh(e_matrix_A)
print("Eigen Vectors: \n{} \n\nEigen Values: \n{}\n".format(eigen_vectors_A, eigen_values_A))

Eigen Vectors: 
[[-0.63440764  0.7729987 ]
 [ 0.7729987   0.63440764]] 

Eigen Values: 
[-2.101926 14.60212 ]

Eigen Vectors: 
[[-0.63440764  0.7729987 ]
 [ 0.7729987   0.63440764]] 

Eigen Values: 
[-2.101926 14.60212 ]

